<a href="https://colab.research.google.com/github/LeSamourai23/Data-Science-Fundamentals/blob/main/freecodecamp_numpy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. The Basics

In [3]:
import numpy as np

In [17]:
# A Simple Array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
# A multi-dimensional array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0], [3.0, 2.0, 1.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [6]:
# Get dimensions of the array
b.ndim

2

In [7]:
# Get Shape
b.shape

(3, 3)

In [8]:
# Get type
a.dtype

dtype('int64')

In [9]:
# Assign type before
c = np.array([1, 3, 5], dtype= 'int16')

c.dtype

dtype('int16')

In [14]:
# Get size
a.itemsize
b.itemsize

8

In [11]:
# Get total size
a.nbytes

24

# 2. Accesing/Changing specific elements, rows, columns, etc

In [7]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [row, column]
# Get 10
a[1, 2]

10

In [24]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [27]:
# Getting very specific things [startindex: enfindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [28]:
# Edit things
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
# 3D example
b = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Get a specific element
# Get 4
b[0, 1, 1]

4

In [32]:
b[: 1 : ]

array([[[1, 2],
        [3, 4]]])

# **3**. Initializing Different Types of Arrays

In [4]:
# All 0s Marix
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [6]:
# Any other number
np.full((3, 3), 69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [9]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [13]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.34252889, 0.81249628],
       [0.22662403, 0.27398328],
       [0.81512286, 0.94537587],
       [0.95146717, 0.78249293]])

In [12]:
# Ranom decimal numbers
np.random.random_sample(a.shape)

array([[3.69820685e-01, 9.01101778e-01, 2.74777354e-01, 7.82361791e-01,
        8.65670563e-01, 9.53785513e-01, 7.80348241e-01],
       [6.89114919e-01, 7.22233620e-04, 4.07669896e-01, 2.80524526e-01,
        6.75600569e-01, 8.44835289e-01, 8.99827132e-01]])

In [14]:
# Random integer values
np.random.randint(7, size=(3, 3))

array([[0, 6, 4],
       [3, 2, 0],
       [6, 5, 4]])

In [15]:
# Indentity Matrix
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis= 0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
# Question: Create the following matrix from absolute
# [[1, 1, 1, 1, 1
#   1, 0, 0, 0, 0
#   1, 0, 9, 0, 1
#   1, 0, 0, 0, 1
#   1, 1, 1, 1, 1]]

output = np.ones((5, 5))

m = np.zeros((3, 3))
m[1, 1] = 9
print(m)

output[1:-1, 1:-1] = m

print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### NOTE: Be careful while copying arrays
When you assign an array to a different variable and make changes, the original array will also be changed

In [23]:
# Don't do this!!!
a = np.array([1, 2, 3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [24]:
# Do this instead
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# 4. Mathematics

## Basic Math Functions

In [25]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [26]:
# Add to each element
a + 2

array([3, 4, 5, 6])

In [27]:
# Subtract from each element
a - 2

array([-1,  0,  1,  2])

In [28]:
# Multiply each element by 2
a * 2

array([2, 4, 6, 8])

In [29]:
# Divide each element by 2
a / 2

array([0.5, 1. , 1.5, 2. ])

In [33]:
b = np.array([6, 5, 4, 3])

In [34]:
# Add array and another array
a + b

array([7, 7, 7, 7])

In [35]:
# Exponents
a ** 2

array([ 1,  4,  9, 16])

In [36]:
# Take the sin of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [37]:
# Take the cosine of all the values
np.cos(b)

array([ 0.96017029,  0.28366219, -0.65364362, -0.9899925 ])

**Additional functionalities:** https://numpy.org/doc/stable/reference/routines.math.html

## Linear Algebra

In [38]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [39]:
# Matrix Multuplication
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [40]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

**Additional functionalities:** https://numpy.org/doc/stable/reference/routines.linalg.html

# 5. Statistics

In [41]:
stats = np.array([[1, 2, 4], [4, 5, 6]])
stats

array([[1, 2, 4],
       [4, 5, 6]])

In [43]:
# Minimum
np.min(stats)

1

In [42]:
# Maximum
np.max(stats)

6

In [ ]:
# Sum of all the elements in the matrix
np.sum(stats)

In [44]:
# Sum of columns
np.sum(stats, axis=0)

array([ 5,  7, 10])

# 6. Reorganizing Arrays


In [45]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
# Reshaping
after = before.reshape((4, 2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# Vertical stacking matrices
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# You can even repeat the stacking
np.vstack([v1, v2, v2, v1, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [52]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# 7. Miscellaneous

#### Local Data from FIle

In [12]:
# Generating data from text
filedata = np.genfromtxt('/content/data.txt', delimiter = ',')
filedata

array([[10.12,  0.45,  0.67],
       [ 0.89,  0.34,  0.21],
       [ 0.76,  0.98,  0.55]])

In [8]:
# generate data as a speicifc data type
filedata = filedata.astype('int32')
filedata

array([[10,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int32)

#### Boolean Masking and Advance Indexing

In [14]:
# Boolean for all the values greater than the target
filedata >= 10

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
# Get all the values greater than the target
filedata[filedata > 0.5]

array([10.12,  0.67,  0.89,  0.76,  0.98,  0.55])

In [15]:
# You can index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a[[0, 1, 8]]

array([1, 2, 9])

In [18]:
# More boolean masking
((filedata > 0.5) & (filedata < 1))

array([[False, False,  True],
       [ True, False, False],
       [ True,  True,  True]])

In [19]:
(~((filedata > 0.5) & (filedata < 1)))

array([[ True,  True, False],
       [False,  True,  True],
       [False, False, False]])